# Generated by Django 4.0.4 on 2022-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Name')),
                ('apellido', models.CharField(max_length=200, verbose_name='Last name')),
            ],
        ),
    ]
