# Generated by Django 4.0.4 on 2022-05-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_personas_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
